### PR TITLE
Splitting themes into store and admin.

### PR DESCRIPTION
**Pull request by pdt256**
This must be merged after https://github.com/inklabs/kommerce-templates/pull/4

### CODE REVIEW

**Comment by pdt256** [comment]
The build will fail due to a dependency on inklabs/kommerce-templates#4

**Comment by pdt256** [comment]
Relates to inklabs/kommerce-core#103

**Comment by pdt256** [comment]
After  inklabs/kommerce-templates#4 has been merged, bin/update-kommerce.sh and commit composer.lock to this PR. That should fix the broken tests.

**Review by jasonraimondi — APPROVED** [review]
Looks good, I think this was really important to have done and it will really make theming your store much easier to get people on boarded.

**Pull request merged**
